#!/bin/bash -e

BACKUP_BASE_DIR=/home/backup
BACKUP_NAME="confluence_backup"
BACKUP_OWNER=backup
BACKUP_GROUP=backup
BACKUP_DIR="$BACKUP_BASE_DIR/$BACKUP_NAME"

CONFLUENCE_DATABASE=confluence
CONFLUENCE_HOME=/home/augmuc/confluence-data

echo "--------------------------------------"
echo $(date)
echo "--------------------------------------"

echo "Create backup directory $BACKUP_DIR"
mkdir -p "$BACKUP_DIR" 

echo "Backup Confluence data directory $CONFLUENCE_HOME to $BACKUP_DIR"
rsync --archive --delete --delete-excluded --exclude-from="$(dirname $0)/excludes" "$CONFLUENCE_HOME/" "$BACKUP_DIR/confluence-data"

echo "Backup database $CONFLUENCE_DATABASE"
mysqldump --quick --single-transaction "$CONFLUENCE_DATABASE" > "$BACKUP_DIR/confluence.sql"

echo "Set new owner ($BACKUP_OWNER) and group ($BACKUP_GROUP) for backup file"
chgrp -R $BACKUP_GROUP "$BACKUP_DIR"
chown -R $BACKUP_OWNER "$BACKUP_DIR"

