#!/bin/bash

REMOTE_HOST=www.aug-muc.de
REMOTE_USER=backup
REMOTE_PATH=/home/backup
LOCAL_PATH=/root/augmuc/backup
PRIVATE_KEY=$LOCAL_PATH/../ssh/augmuc_backup_rsa
LOGROTATE="/usr/sbin/logrotate --force --state $LOCAL_PATH/augmuc_backup.logrotate.state $LOCAL_PATH/augmuc_backup.logrotate.options"

echo "----------------------------------"
echo $(date)
echo "----------------------------------"

if [ -n "$LOGROTATE" ]; then
	echo "Rotate old backup"
	$LOGROTATE || "Cannot rotate backup. This maybe an error"
fi

echo "Synchronize backup from $REMOTE_HOST"
/usr/bin/scp -i "$PRIVATE_KEY" $REMOTE_USER@$REMOTE_HOST:"$REMOTE_PATH" "$LOCAL_PATH" > /tmp/augmuc_backup.log 2>&1 || cat /tmp/augmuc_backup.log | /root/sendmail 'Confluence Backup <noreply@aug-muc.de>' "There is a problem with the backup of Confluence" "leo.vonklenze@tngtech.com"

