#!/bin/bash

REMOTE_HOST=www.aug-muc.de
REMOTE_USER=backup
REMOTE_PATH=/home/backup/confluence_backup
LOCAL_PATH=/root/augmuc/backup
PRIVATE_KEY=/root/augmuc/ssh/augmuc_backup_rsa

echo "----------------------------------"
echo $(date)
echo "----------------------------------"

echo "Synchronize backup from $REMOTE_HOST"
/usr/bin/rsync --archive --delete --rsh "ssh -i $PRIVATE_KEY" $REMOTE_USER@$REMOTE_HOST:"$REMOTE_PATH/" "$LOCAL_PATH/" > /tmp/augmuc_backup.log 2>&1 || cat /tmp/augmuc_backup.log | /root/sendmail 'Confluence Backup <noreply@aug-muc.de>' "There is a problem with the backup of Confluence" "leo.vonklenze@tngtech.com"

cat /tmp/augmuc_backup.log

